# Generated by Django 4.1.1 on 2022-09-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="author",
            field=models.CharField(default="acm", max_length=50),
        ),
    ]
