# Generated by Django 3.0.7 on 2022-09-27 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20220925_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
