# Generated by Django 3.0.7 on 2022-12-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20220927_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='exploreLink',
            field=models.URLField(blank=True),
        ),
    ]
